### ISSUE TITLE
Create REST API to get user based on using userIdentifier

### ISSUE THREAD

**Issue by reehanlalkhan** [springboardfoundation/NeedNetService#13]
Create REST API to get user based on using userIdentifier
- Add the GET API in UserRegistrationController.java
- The userIdentifier will be passed as Request Parameter
- Get the Request Parameter using @RequestParam
- The key will userIdentifier and value will be passed by the user
- Using this userIdentifier search the DB and fetch the User
- Return the User, if found, else return 204 No Content
- Write the method to fetch entity from DB based on userIdentifier in UserRepository

**Comment by waheeduddin1357** [comment]
Create REST API to get user based on using userIdentifier
